{% set name = "ixwebsocket" %}
{% set version = "11.4.5" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/machinezone/IXWebSocket/archive/v{{ version }}.tar.gz
  sha256: c5fc225edec32bf7d583e55347ef2c9c4940d005c13ef5e848354a85602f5fd6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - zlib
    - openssl
  run:

outputs:
  - name: libixwebsocket
    build:
      run_exports:
        - {{ pin_subpackage('libixwebsocket', max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - zlib
        - openssl
      run:
    files:
      - lib/libixwebsocket.so.*  # [linux]
      - lib/libixwebsocket.*.dylib  # [osx]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libixwebsocket${SHLIB_EXT}  # [unix]

  - name: ixwebsocket
    build:
      run_exports:
        - {{ pin_subpackage('libixwebsocket', max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage('libixwebsocket', exact=True) }}
      run:
        - {{ pin_subpackage('libixwebsocket', exact=True) }}
    files:
      - lib/libixwebsocket.so  # [linux]
      - lib/libixwebsocket.dylib  # [osx]
      - include/ixwebsocket  # [unix]
      - lib/cmake/ixwebsocket  # [unix]
      - lib/pkgconfig/ixwebsocket.pc  # [unix]
      - bin/ws  # [unix]
    test:
      commands:
        - ws --help


about:
  home: https://machinezone.github.io/IXWebSocket/
  summary: IXWebSocket is a C++ library for WebSocket client and server development.
  description: |
    IXWebSocket is a C++ library for WebSocket client and server development. It has
    minimal dependencies (no boost), is very simple to use and support everything you'll
    likely need for websocket dev (SSL, deflate compression, compiles on most platforms, etc...).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://machinezone.github.io/IXWebSocket
  dev_url: https://github.com/machinezone/IXWebSocket

extra:
  recipe-maintainers:
    - zklaus
    - timkpaine
